# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  external_labels:
      monitor: 'docker-m83'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    scrape_intefval: 5s
    static_configs:
      - targets: ['localhost:9100']